services:
  data_collector:
    image: data_collector:latest
    volumes:
      - industria-dataflow-volume:/data

  model_service:
    image: model_service:latest
    volumes:
      - industria-dataflow-volume:/data
    depends_on:
      - data_collector

  api_service:
    image: api_service:latest
    volumes:
      - industria-dataflow-volume:/data
    ports:
      - 8000:8000
    depends_on:
      - model_service

  frontend:
    image: frontend:latest
    ports:
      - "8080:80"
    depends_on:
      - api_service

volumes:
  industria-dataflow-volume:
