services:
  data_collector:
    build: ./data_collector
    container_name: data_collector
    volumes:
      - industria-dataflow-volume:/data

  model_service:
    build: ./model_service
    container_name: model_service
    volumes:
      - industria-dataflow-volume:/data
    depends_on:
      - data_collector

  api_service:
    build: ./api_service
    container_name: api_service
    volumes:
      - industria-dataflow-volume:/data
    ports:
      - 8000:8000
    depends_on:
      - model_service

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - api_service

volumes:
  industria-dataflow-volume:
